### ISSUE TITLE
Cannot use 'in' operator to search for 'limit' 

### ISSUE THREAD

**Issue by antolinos** [panosc-eu/search-api#69] opened 2022-09-08 13:19 UTC
Hi,

**Describe the bug**

I am trying to fix the problem when retrieving the list of members linked to a document.

In the [UI](https://data.panosc.eu/search/?q=diffraction) the following request is triggered when expanding the member list:
https://federated.panosc.ess.eu/api/documents/59848051?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50}

returning the error below:
```
{"error":{"name":"TypeError","status":500,"message":"Cannot use 'in' operator to search for 'limit' in 59848051","stack":"TypeError: Cannot use 'in' operator to search for 'limit' in 59848051\n    at /home/node/app/server/connectors/distributedConnector.js:147:70\n    at Array.map (<anonymous>)\n    at Function.remoteMethodProxy [as findById] (/home/node/app/server/connectors/distributedConnector.js:146:10)\n    at SharedMethod.invoke (/home/node/app/node_modules/loopback/node_modules/strong-remoting/lib/shared-method.js:263:25)\n    at HttpContext.invoke (/home/node/app/node_modules/loopback/node_modules/strong-remoting/lib/http-context.js:389:12)\n    at phaseInvoke (/home/node/app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:654:9)\n    at runHandler (/home/node/app/node_modules/loopback-phase/lib/phase.js:135:5)\n    at iterate (/home/node/app/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)\n    at Object.async.eachSeries (/home/node/app/node_modules/loopback-phase/node_modules/async/lib/async.js:162:9)\n    at runHandlers (/home/node/app/node_modules/loopback-phase/lib/phase.js:144:13)\n    at iterate (/home/node/app/node_modules/loopback-phase/node_modules/async/lib/async.js:146:13)\n    at /home/node/app/node_modules/loopback-phase/node_modules/async/lib/async.js:157:25\n    at /home/node/app/node_modules/loopback-phase/node_modules/async/lib/async.js:154:25\n    at execStack (/home/node/app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:493:7)\n    at RemoteObjects.execHooks (/home/node/app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:497:10)\n    at phaseBeforeInvoke (/home/node/app/node_modules/loopback/node_modules/strong-remoting/lib/remote-objects.js:650:10)"}}
```

There are two things that I have noticed:
1) I have no error trace on my side. It makes me think that the request gets intercepted before calling the ESRF panosc search api deployed via icatplus.esrf.fr
2) The very same query seems to work on our local panosc deployement:
https://icatplus.esrf.fr/api/Documents/59848051?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50}

I was wondering what is wrong. I can see that for others (ESS, for instance) it works so I presume that is somehow related to my deployment but I can not understand how.

**To Reproduce**

1. Go to [here](https://federated.panosc.ess.eu/api/documents/59848051?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50})
2. Compare with [this](https://icatplus.esrf.fr/api/Documents/59848051?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50})

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/2901169/189131589-98c1cc0e-eeb9-49a5-b483-42871bfcb6c9.png)

**Desktop (please complete the following information):**

**Comment by nitrosx** [comment] 2022-10-10 14:44
Alex
I checked and the first url and I'm able to reproduce the issue.
The federated search errors because you are requesting a specific document with the addition of a filter.
I see the issue...

I need to check if our PaNOSC API has the same behavior.

Interesting enough, if you remove the document id, the query is successful:
[https://federated.panosc.ess.eu/api/documents/?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50}](https://federated.panosc.ess.eu/api/documents/?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50})

**Comment by nitrosx** [comment] 2022-10-10 14:48
I tested our PaNOSC search api and it works:
https://search.panosc.ess.eu/api/documents/10.17199%2F03dd9804-1b04-4d36-b0fb-cf66e9891e7d?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50}

**Comment by nitrosx** [comment] 2022-10-10 14:49
I will check the federated search and see where the issue is

**Comment by antolinos** [comment] 2022-10-10 14:56
Hi @nitrosx,

Thanks for looking into this.

The query is used on the panosc data portal when retrieving the members of an investigation.
It works for others but we get an error though. 

For others, it works with and without `documentId`:

Example:
https://federated.panosc.ess.eu/api/documents/ILL_PROPOSAL.3-03-767?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50}

However, the same query will not work for the ESRF:
https://federated.panosc.ess.eu/api/documents/59848051?filter={%22include%22:[{%22relation%22:%22members%22,%22scope%22:{%22include%22:[{%22relation%22:%22person%22},{%22relation%22:%22affiliation%22}]}}],%22limit%22:50}

It is clearly a problem specific to our implementation however I realized that the query `works locally`:
https://icatplus.esrf.fr/api/Documents/59848051?filter={"include":[{"relation":"members","scope":{"include":[{"relation":"person"},{"relation":"affiliation"}]}}],"limit":50}

This is why I can not debug on my side but we are doing/returning something wrong and the federated search does not like it....
Is the federated API modifying the filter parameter on the fly or something?

**Comment by nitrosx** [comment] 2022-10-10 15:20
Closing this issue as I opened one on the correct repository:
[panosc federated search service issue #9](https://github.com/panosc-eu/panosc-federated-search-service/issues/9)

Please refer to the new issue for further comments

**Closed as completed by nitrosx** 2022-10-10 15:20 UTC
